development:
  adapter: async

test:
  adapter: async

production: &redis_cable
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: standalone-pwb_production

staging:
  <<: *redis_cable
  channel_prefix: standalone-pwb_staging
