# PostgreSQL. Versions 9.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: pwb_development
  tenant_shard_1:
    <<: *default
    database: pwb_development_shard_1
    migrations_paths: db/tenant_shard_1_migrate
  demo_shard:
    <<: *default
    database: pwb_demo_shard
    migrations_paths: db/demo_shard_migrate

  # The specified database role being used to connect to postgres.
  # To create additional roles in postgres see `$ createuser --help`.
  # When left blank, postgres will use the default role. This is
  # the same name as the operating system user that initialized the database.
  #username: pwb

  # The password associated with the postgres role (username).
  #password:

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  #host: localhost

  # The TCP port the server listens on. Defaults to 5432.
  # If your server runs on a different port number, change accordingly.
  #port: 5432

  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # Defaults to warning.
  #min_messages: notice

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  primary:
    <<: *default
    database: pwb_test
  tenant_shard_1:
    <<: *default
    database: pwb_test_shard_1
    migrations_paths: db/tenant_shard_1_migrate
  demo_shard:
    <<: *default
    database: pwb_test_demo_shard
    migrations_paths: db/demo_shard_migrate

# E2E testing environment for Playwright tests
# Uses a separate database to keep test data isolated
e2e:
  primary:
    <<: *default
    database: pwb_e2e
  tenant_shard_1:
    <<: *default
    database: pwb_e2e_shard_1
    migrations_paths: db/tenant_shard_1_migrate
  demo_shard:
    <<: *default
    database: pwb_e2e_demo_shard
    migrations_paths: db/demo_shard_migrate


# As with config/secrets.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is
# ever seen by anyone, they now have access to your database.
#
# Instead, provide the password as a unix environment variable when you boot
# the app. Read http://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full rundown on how to provide these environment variables in a
# production deployment.
#
# On Heroku and other platform providers, you may have a full connection URL
# available as an environment variable. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# You can use this database configuration with:
#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
production:
  primary:
    <<: *default
    # When url is provided (Dokku/Heroku), it overrides database/username/password
    # These fallbacks are only used if no URL is set
    database: pwb_production
    username: pwb
    url: <%= ENV['PWB_DATABASE_URL'] || ENV['DATABASE_URL'] %>
    password: <%= ENV['PWB_DATABASE_PASSWORD'] %>
    prepared_statements: false
  <% if ENV['PWB_TENANT_SHARD_1_DATABASE_URL'].present? %>
  tenant_shard_1:
    <<: *default
    # URL from Dokku: dokku postgres:link pwb-shard-1 app --alias PWB_TENANT_SHARD_1_DATABASE
    url: <%= ENV['PWB_TENANT_SHARD_1_DATABASE_URL'] %>
    migrations_paths: db/tenant_shard_1_migrate
    prepared_statements: false
  <% end %>
  <% if ENV['PWB_DEMO_SHARD_DATABASE_URL'].present? %>
  demo_shard:
    <<: *default
    # URL from Dokku: dokku postgres:link pwb-demo-shard app --alias PWB_DEMO_SHARD_DATABASE
    url: <%= ENV['PWB_DEMO_SHARD_DATABASE_URL'] %>
    migrations_paths: db/demo_shard_migrate
    prepared_statements: false
  <% end %>

staging:
  primary:
    <<: *default
    # Fallbacks only used if no URL is set
    database: pwb_staging
    username: pwb
    url: <%= ENV['PWB_STAGING_DATABASE_URL'] || ENV['PWB_DATABASE_URL'] || ENV['DATABASE_URL'] %>
    password: <%= ENV['PWB_STAGING_DATABASE_PASSWORD'] || ENV['PWB_DATABASE_PASSWORD'] %>
    prepared_statements: false
  <% if ENV['PWB_STAGING_TENANT_SHARD_1_DATABASE_URL'].present? %>
  tenant_shard_1:
    <<: *default
    url: <%= ENV['PWB_STAGING_TENANT_SHARD_1_DATABASE_URL'] %>
    migrations_paths: db/tenant_shard_1_migrate
    prepared_statements: false
  <% end %>
  <% if ENV['PWB_STAGING_DEMO_SHARD_DATABASE_URL'].present? %>
  demo_shard:
    <<: *default
    url: <%= ENV['PWB_STAGING_DEMO_SHARD_DATABASE_URL'] %>
    migrations_paths: db/demo_shard_migrate
    prepared_statements: false
  <% end %>
